---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "dagger.fullname" . }}-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dagger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      name: {{ include "dagger.fullname" . }}-engine
  template:
    metadata:
      {{- if (or .Values.engine.config .Values.magicache.enabled) }}
      annotations:
        {{- if .Values.engine.config }}
        checksum/config: {{ include (print $.Template.BasePath "/engine-config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.magicache.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/magicache-secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
      labels:
        name: {{ include "dagger.fullname" . }}-engine
        {{- include "dagger.labels" . | nindent 8 }}
    spec:
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- with .Values.engine.affinity.nodeAffinity }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        podAntiAffinity:
          # preferredDuringSchedulingIgnoredDuringExecution:
          #   - weight: 100
          #     podAffinityTerm:
          #       labelSelector:
          #         matchExpressions:
          #           - key: app.kubernetes.io/name
          #             operator: In
          #             values:
          #               - {{ include "dagger.name" . }}
          #       namespaces: [ {{ .Release.Namespace }} ]
          #       topologyKey: kubernetes.io/hostname
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "dagger.name" . }}
              namespaces: [ {{ .Release.Namespace }} ]
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 0
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: {{ include "dagger.serviceAccountName" . }}
      {{- if .Values.engine.priorityClassName }}
      priorityClassName: {{ .Values.engine.priorityClassName }}
      {{- end }}
      containers:
        - name: dagger-engine
          image: {{ .Values.engine.image.repository }}:{{ if .Values.engine.image.tag }}{{ .Values.engine.image.tag }}{{ else }}v{{ .Chart.AppVersion }}{{ end }}
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          {{- if .Values.engine.args }}
          args:
            {{- toYaml .Values.engine.args | nindent 12 }}
          {{- end }}
          {{- if .Values.magicache.enabled }}
          env:
          - name: _EXPERIMENTAL_DAGGER_CACHESERVICE_URL
            value: {{ required "A magicache url is required" .Values.magicache.url }}
          envFrom:
          - secretRef:
              {{- if .Values.magicache.secretName }}
              name: {{ .Values.magicache.secretName }}
              {{- else}}
              name: {{ include "dagger.fullname" . }}-magicache-token
              {{- end}}
          {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          resources: {{- toYaml .Values.engine.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: [ "buildctl", "debug", "workers" ]
            {{- if .Values.engine.readinessProbeSettings }}
            {{- toYaml .Values.engine.readinessProbeSettings | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: varlibdagger
              mountPath: /var/lib/dagger
            - name: varrundagger
              mountPath: /var/run/buildkit
            {{- if .Values.engine.config }}
            - name: dagger-engine-config
              mountPath: /etc/dagger/engine.toml
              subPath: engine.toml
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.engine.terminationGracePeriodSeconds }}
      volumes:

        # This is the cache
        - name: varlibdagger
          {{- if .Values.engine.nfsCache }}
          nfs:
            {{- toYaml .Values.engine.nfsCache | nindent 12 }}
            readOnly: false
          {{- else }}
          hostPath:
            path: /var/lib/dagger
          {{- end }}

        # This is for sharing the /var/run/dagger/buildkitd.sock with host.
        # In our context though, the dagger CLI uses the value of the
        # _EXPERIMENTAL_DAGGER_RUNNER_HOST environment variable instead.
        - name: varrundagger
          hostPath:
            path: /var/run/dagger

        {{- if .Values.engine.config }}
        - name: dagger-engine-config
          configMap:
            name: {{ include "dagger.fullname" . }}-engine-config
            items:
              - key: engine.toml
                path: engine.toml
        {{- end }}
