{{- if .Values.engine.newServiceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "dagger.serviceAccountName" . }}
  labels:
    {{- include "dagger.labels" . | nindent 4 }}
  {{- with .Values.engine.newServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
